draft: spks billing
vshn/billing-collector-cloudservices pull request #78
Opened 2024-04-02 11:45 UTC by wejdross

Add automated billing for spks. This code is intended to run as deployment and execute once per 24h. UoM is set to correspond:  https://docs.central.vshn.ch/unit-of-measurements.html#_uoms_for_metered_billing

2024-04-03 08:03 UTC, Kidswiss requested changes
Just some small things.

2024-04-03 08:03 UTC, Kidswiss commented on pkg/cmd/spks.go
> +			// it will be run via kubernetes cronjob at midnight
It uses a ticker further below, so this comment doesn't seem valid anymore.

2024-04-03 08:03 UTC, Kidswiss commented on pkg/cmd/spks.go
> +						panic(err)
Please don't use panic here and return the error. This way the error is handled by the cli library.

2024-04-03 08:45 UTC, wejdross commented on pkg/cmd/spks.go
> +			from := time.Now().In(location).UTC()
that's very good catch, I missed it because Odoo simply accepted such payload :D

2024-04-03 08:46 UTC, wejdross commented
I added first run of the function before for{} loop to avoid situation in which because of constant restarts we won't send any data

2024-04-03 09:05 UTC, Kidswiss commented
> I added first run of the function before for{} loop to avoid situation in which because of constant restarts we won't send any data

Should be fine AFAIK Odoo handles multiple entries for the same timespan gracefully.

2024-04-03 09:05 UTC, Kidswiss approved these changes

2024-04-04 05:56 UTC, tobru requested changes

2024-04-04 05:56 UTC, tobru commented on pkg/cmd/spks.go
> +			&cli.StringFlag{Name: "sales-order", Usage: "Sales order for APPUiO Managed clusters",
```suggestion
			&cli.StringFlag{Name: "sales-order", Usage: "Sales order to report billing data to",
```

This reporting tool isn't about APPUiO Managed

2024-04-04 05:56 UTC, tobru commented on pkg/cmd/spks.go
> +			&cli.StringFlag{Name: "unit-id", Usage: "Unit ID for the consumed units",
```suggestion
			&cli.StringFlag{Name: "unit-id", Usage: "Metered Billing UoM ID for the consumed units",
```

This is more clear IMHO

2024-04-04 05:56 UTC, tobru commented on pkg/cmd/spks.go
> +				return fmt.Errorf("load loaction: %w", err)
```suggestion
				return fmt.Errorf("load location: %w", err)
```

2024-04-04 05:56 UTC, tobru commented on pkg/cmd/spks.go
> +					ItemGroupDescription: "SPKS",
This doesn't make a lot of sense. These two parameters end up in the invoice and should be descriptive to the consumer of the invoice (see https://docs.central.vshn.ch/metered-billing-data-ingestion.html#_json_structure). See example JSON in SPKS-863 for the "ItemDescription". "ItemGroupDescription" should be removed, it's optional anyway.

2024-04-16 13:04 UTC, merged